apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: 543816070942.dkr.ecr.us-east-1.amazonaws.com/shubham-react-movieapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: REACT_APP_API_URL
          value: "a343e5e3db5224b10968afabc3cae920-809764658.us-east-1.elb.amazonaws.com"
