apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend   # Must match your Deployment label
  ports:
    - port: 80        # Service port inside cluster
      targetPort: 80  # Container port
      nodePort: 30080 # Optional: choose NodePort (range 30000–32767)
