apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  type: LoadBalancer   # Expose frontend publicly
  selector:
    app: frontend      # Must match labels in your Deployment
  ports:
    - port: 80         # Port exposed outside
      targetPort: 80   # Port inside the container
