name: React Frontend CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run Tests and Generate Coverage
        continue-on-error: true
        run: |
          echo "Running tests..."
          npm test -- --watchAll=false

      - name: Upload Coverage Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: Build
        run: CI=false npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ARN }}
          role-session-name: shubham_movie_app_role
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy to S3
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          S3_BUCKET: ${{ vars.S3_BUCKET }}
        run: |
          aws s3 sync --delete ./build/ s3://$S3_BUCKET/
